#ifndef QTWIDGET_PLANETOSM_DESIGNER_GLOBAL_H
#define QTWIDGET_PLANETOSM_DESIGNER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTWIDGET_PLANETOSM_DESIGNER_LIBRARY)
#  define QTWIDGET_PLANETOSM_DESIGNERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTWIDGET_PLANETOSM_DESIGNERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTWIDGET_PLANETOSM_DESIGNER_GLOBAL_H
